title: Vespa. Big data. Real time.
description: > # this means to ignore newlines until "baseurl:"
  Vespa - the big data serving platform
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vespa.ai" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  vespa-engine

defaults:
  -
    scope:
      path: "/documentation/*"
    values:
      layout: "documentation"
      index: true
  -
    scope:
      path: "/pages/*"
    values:
      layout: "page"
      index: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

